[tool.black]
line-length = 120
# Exclude everything in the .gitignore, but also:
extend-exclude = '''
/(
    notebooks
    | docs
)/
'''

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 120
skip_glob = ["docs/*", "notebooks/*"]
[tool.jupytext]
formats = "ipynb,py:light"
